const data = {
    products:[
        {
            _id:'1',
            name: 'Formal Shirt',
            category: 'Shirt',
            image: 'images/fs1.jpeg',
            price:  $1460,
            brand: 'Cool Colors',
            rating: 4.8,
            numReviews: 75,
            description: 'True to fit size',
        },
        {
            _id:'2',
            name: 'Jeans Shirt',
            category: 'Shirt',
            image: 'images/js1.jpeg',
            price: $620,
            brand: 'Lee Cooper',
            rating: 4.1,
            numReviews: 42,
            description: 'True to fit size',
        },
        {
            _id:'3',
            name: 'Casual Shirt',
            category: 'Shirt',
            image: 'images/cs1.jpeg',
            price: $840,
            brand: 'USPA',
            rating: 4.5,
            numReviews: 103,
            description: 'True to fit size',
        },
        {
            _id:'4',
            name: 'Blue Jeans',
            category: 'Pants',
            image: 'images/jeans1.jpeg',
            price: $1100,
            brand: 'Pepe Jeans',
            rating: 4.2,
            numReviews: 157,
            description: 'True to fit size',
        },
        {
            _id:'5',
            name: 'Torn Jeans',
            category: 'Pants',
            image: 'images/tj1.jpeg',
            price: $430,
            brand: 'Mufti',
            rating: 3.1,
            numReviews: 92,
            description: 'True to fit size',
        },
        {
            _id:'6',
            name: 'Black Jeans',
            category: 'Pants',
            image: 'images/blaj1.jpeg',
            price: $960,
            brand: 'Spykar',
            rating: 4.4,
            numReviews: 171,
            description: 'True to fit size',
        },
        {
            _id:'7',
            name: 'Formal Pant',
            category: 'Pants',
            image: 'images/p2.jpg',
            price: $1670,
            brand: 'Allen Solly',
            rating: 4.7,
            numReviews: 111,
            description: 'True to fit size',
        },
        {
            _id:'8',
            name: 'Leather Belt',
            category: 'Pants',
            image: 'images/be1.jpeg',
            price: $320,
            brand: 'Woodland',
            rating: 4.0,
            numReviews: 183,
            description: 'High Quality',
        },
        {
            _id:'9',
            name: 'T-Shirt',
            category: 'Leisure Wear',
            image: 'images/tshirt1.jpeg',
            price: $450,
            brand: 'USPA',
            rating: 4.3,
            numReviews: 135,
            description: 'True to fit size',
        },
        {
            _id:'10',
            name: 'Sweatshirt',
            category: 'Leisure Wear',
            image: 'images/sws1.jpeg',
            price: $800,
            brand: 'Flying Machine',
            rating: 3.9,
            numReviews: 89,
            description: 'True to fit size',
        },
        {
            _id:'11',
            name: 'Hoodie',
            category: 'Leisure Wear',
            image: 'images/h1.jpeg',
            price: $800,
            brand: 'Levis',
            rating: 4.3,
            numReviews: 63,
            description: 'True to fit size',
        },
        {
            _id:'12',
            name: 'Track Pants',
            category: 'Leisure Wear',
            image: 'images/track1.jpeg',
            price: $780,
            brand: 'UCB',
            rating: 4.1,
            numReviews: 158,
            description: 'True to fit size',
        },
        {
            _id:'13',
            name: 'Shorts',
            category: 'Leisure Wear',
            image: 'images/sh1.jpeg',
            price: $650,
            brand: 'HRX',
            rating: 4.3,
            numReviews: 139,
            description: 'True to fit size',
        },
        {
            _id:'14',
            name: 'Boxers',
            category: 'Leisure Wear',
            image: 'images/boxer1.jpeg',
            price: $390,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 97,
            description: 'True to fit size',
        },
        {
            _id:'15',
            name: 'Under-Garments pack',
            category: 'Inner-Wear',
            image: 'images/ug1.jpeg',
            price: $1000,
            brand: 'Dixcy Scott',
            rating: 4.1,
            numReviews: 91,
            description: 'True to fit size',
        },
        {
            _id:'16',
            name: 'Vest',
            category: 'Inner-Wear',
            image: 'images/v1.jpeg',
            price: $500,
            brand: 'Puma',
            rating: 4.6,
            numReviews: 152,
            description: 'True to fit size',
        },
        {
            _id:'17',
            name: 'Under-Wear',
            category: 'Inner-Wear',
            image: 'images/uw1.jpeg',
            price: $300,
            brand: 'Calvin Klein',
            rating: 4.2,
            numReviews: 109,
            description: 'True to fit size',
        },
        {
            _id:'18',
            name: 'Traditional Shirt',
            category: 'Traditional Wear',
            image: 'images/ts1.jpeg',
            price: $1500,
            brand: 'Ramraj',
            rating: 4.1,
            numReviews: 163,
            description: 'True to fit size',
        },
        {
            _id:'19',
            name: 'Velcro Dothi',
            category: 'Traditional Wear',
            image: 'images/vd1.jpeg',
            price: $1300,
            brand: 'Uthayam',
            rating: 4.2,
            numReviews: 132,
            description: 'True to fit size',
        },
        {
            _id:'20',
            name: 'Pack of Traditional Wear',
            category: 'Traditional Wear',
            image: 'images/tw1.jpeg',
            price: $2500,
            brand: 'Khadims',
            rating: 4.1,
            numReviews: 166,
            description: 'True to fit size',
        },
        {
            _id:'21',
            name: 'Suit',
            category: 'Suitings',
            image: 'images/suit1.jpeg',
            price: $2900,
            brand: 'Van Husen',
            rating: 4.0,
            numReviews: 85,
            description: 'True to fit size',
        },
        {
            _id:'22',
            name: 'Blazer',
            category: 'Suitings',
            image: 'images/blazer1.jpeg',
            price: $3700,
            brand: 'Raymond',
            rating: 4.7,
            numReviews: 73,
            description: 'True to fit size',
        },
        {
            _id:'22',
            name: 'Tie',
            category: 'Suitings',
            image: 'images/tie1.jpeg',
            price: $200,
            brand: 'Arrow',
            rating: 4.0,
            numReviews: 120,
            description: 'True to fit size',
        },
    ],
};
export default data;